### ISSUE TITLE
Mention flake8-cognitive-complexity in readme

### ISSUE THREAD

**Issue by Melevir** [Melevir/cognitive_complexity#10]
Most common usecase of using this library is via `flake8-cognitive-complexity`. Readme has to say this explicitly.

**Comment by Melevir** [comment]
This one is still valid.

**Comment by fhightower** [comment]
@Melevir : I'd like to work on this issue if I may.

Also, thanks for your work on this project! Was excited to find it and have benefited from it already.

**Comment by Melevir** [comment]
Great, I would be glad to merge a PR from you :)

> Also, thanks for your work on this project! Was excited to find it and have benefited from it already.

Thanks for using it!
