### ISSUE TITLE
License is missing in repo and pypi release tarball

### ISSUE THREAD

**Issue by priv-kweihmann** [Melevir/cognitive_complexity#18]
An explicit LICENSE file is missing in repo and pypi release tarball - please add such information

**Comment by Melevir** [comment]
Can you please describe case, when missing of theese is an issue?

**Comment by priv-kweihmann** [comment]
Currently I'm not able to get clearance by legal for using it in a commercial environment, as no explicit LICENSE is existing atm.
Within YOCTO/OpenEmbedded the sources are being pulled from pypi.org - the build system itself takes care of licensing conflicts, but as the file is not existing it is more of an educated guess - nothing I would get through any kind of legal clearance.

Your module is used by https://github.com/wemake-services/wemake-python-styleguide which is really nice to have - so I either include your module or have to completely remove using the above stated wemake-python-styleguide.

https://pypi.org/project/cognitive-complexity/ states that it is licensed as MIT, so to get through legal clearance all I need is a corresponding LICENSE file within in the pypi.org release tarball (which implies having it in the repo too)

**Comment by Melevir** [comment]
Added in 1.2.0
