### ISSUE TITLE
Document try complexity computation

### ISSUE THREAD

**Issue by HarrySky** [Melevir/cognitive_complexity#20]
Hi, thanks for this great tool :smile: I was scratching my head when adding/removing any lines from `try` block was influencing cognitive complexity and searched in your documentation and then code why is that and found this line in code:

https://github.com/Melevir/cognitive_complexity/blob/1df07df7adf88bc2c002e4bf85da28c18bfbd086/cognitive_complexity/utils/ast.py#L40

It means that any line added inside try block will increment complexity (code below gives complexity 4)

```python
def a(b, c):
    try:
        print(1)
        print(2)
        print(3)
        print(4)
    except Exception:
        raise
```

This behavior is unexpected as it was not mentioned in SonarSource links provided, can we document it here or in flake8 extension? Thanks

**Comment by Anders-Steen** [comment]
This is not a documentation fault but a bug.
I think I fixed the issue. 
```python
def a(b, c):
    try:
        print(1)
        print(2)
        print(3)
        print(4)
    except Exception:  # +1 (nesting 0)
        raise                  # +0 (nesting 1)
```
