### ISSUE TITLE
Not increment nesting for decorators

### ISSUE THREAD

**Issue by Melevir** [Melevir/cognitive_complexity#4]
> Python’s decorator idiom allows additional behavior to be added to an existing function
without modifying the function itself. This addition is accomplished with the use of nested
functions in the decorator providing the additional behavior. In order not to penalize Python
coders for the use of a common feature of their language, an exception has been added.
However, an attempt has been made to define the exception narrowly. Specifically, to be
eligible for the exception, a function may contain only a nested function and a return
statement.

This is valid after #3 is done.

**Comment by pkolbus** [comment]
I'm starting on this to help get the calculations aligned with the spec. At the moment, I have the functions from Appendix A of the spec as test cases, and an `is_decorator()` helper defined, but am still working out where to connect that so it applies to the top-level `FunctionDef`.
